# Use root/example as user/password credentials
version: '3.1'

services:
  lcportal:
    image: lcportal
    build: .
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS = -Dspring.profiles.active=docker
      - "SPRING_PROFILES_ACTIVE=docker" 
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: root
       ME_CONFIG_MONGODB_ADMINPASSWORD: example
